In [1]:
import numpy as np
B=np.array([[1,2,3,4],[5,6,7,8],[9,0,1,2]])
B

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 1, 2]])

In [2]:
B[:2,:3]

array([[1, 2, 3],
       [5, 6, 7]])

In [3]:
B[:3,::2]

array([[1, 3],
       [5, 7],
       [9, 1]])

In [4]:
B[::-1,::-1]

array([[2, 1, 0, 9],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])