In [1]:
import numpy as np
arr = np.arange(16).reshape((4,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [2]:
upper,lower = np.vsplit(arr,2)       #Tách theo trục ngang
print("Kết quả sau khi tách từ mảng ban đầu \n")
print(upper,"\n")
print(lower,"\n")

Kết quả sau khi tách từ mảng ban đầu 

[[0 1 2 3]
 [4 5 6 7]] 

[[ 8  9 10 11]
 [12 13 14 15]] 



In [3]:
left,right=np.hsplit(arr,2) #Tách theo trục dọc
print("Kết quả sau khi tách từ mảng ban đầu \n")
print(left,"\n")
print(right,"\n")

Kết quả sau khi tách từ mảng ban đầu 

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]] 

