In [1]:
import numpy as np
arr = np.array([0,1,2])
arr

array([0, 1, 2])

In [2]:
M=np.ones((3,3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [3]:
arr + M

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])