In [3]:
import pandas as pd
population = pd.Series({'Hà Nội':8330803,
                    'Quảng Ninh':1358085,
                    'Nam Định':1836270,
                    'Đà Nẵng':1195490,
                    'TP.Hồ Chí Minh':9411805})
area = pd.Series({'Hà Nội':3358.9,
             'Quảng Ninh':6177.7,
             'Nam Định':1668.0,
             'Đà Nẵng':1284.9,
             'TP.Hồ Chí Minh':2061.0})
data = pd.DataFrame({'Dân số':population,'Diện tích':area})
data

Dân số  Diện tích
Hà Nội          8330803     3358.9
Quảng Ninh      1358085     6177.7
Nam Định        1836270     1668.0
Đà Nẵng         1195490     1284.9
TP.Hồ Chí Minh  9411805     2061.0

In [4]:
data['Dân số'] #Lấy cột 'Dân số'

Hà Nội            8330803
Quảng Ninh        1358085
Nam Định          1836270
Đà Nẵng           1195490
TP.Hồ Chí Minh    9411805
Name: Dân số, dtype: int64

In [5]:
data['population']=data['Dân số']
print(data)

                 Dân số  Diện tích  population
Hà Nội          8330803     3358.9     8330803
Quảng Ninh      1358085     6177.7     1358085
Nam Định        1836270     1668.0     1836270
Đà Nẵng         1195490     1284.9     1195490
TP.Hồ Chí Minh  9411805     2061.0     9411805


In [6]:
data.population 

Hà Nội            8330803
Quảng Ninh        1358085
Nam Định          1836270
Đà Nẵng           1195490
TP.Hồ Chí Minh    9411805
Name: population, dtype: int64

In [7]:
data['Mật độ']=data['Dân số']/ data['Diện tích']
data

Dân số  Diện tích  population       Mật độ
Hà Nội          8330803     3358.9     8330803  2480.217631
Quảng Ninh      1358085     6177.7     1358085   219.836671
Nam Định        1836270     1668.0     1836270  1100.881295
Đà Nẵng         1195490     1284.9     1195490   930.414818
TP.Hồ Chí Minh  9411805     2061.0     9411805  4566.620573

In [10]:
arr_data = data.values # Lấy mảng dữ liệu gốc từ DataFrame
print(arr_data) 
print('Kiểu dữ liệu của arr_data là:',type(arr_data))

[[8.33080300e+06 3.35890000e+03 8.33080300e+06 2.48021763e+03]
 [1.35808500e+06 6.17770000e+03 1.35808500e+06 2.19836671e+02]
 [1.83627000e+06 1.66800000e+03 1.83627000e+06 1.10088129e+03]
 [1.19549000e+06 1.28490000e+03 1.19549000e+06 9.30414818e+02]
 [9.41180500e+06 2.06100000e+03 9.41180500e+06 4.56662057e+03]]
Kiểu dữ liệu của arr_data là: <class 'numpy.ndarray'>


In [11]:
#### VD4.4.2.2
data.T

Hà Nội    Quảng Ninh      Nam Định       Đà Nẵng  \
Dân số      8.330803e+06  1.358085e+06  1.836270e+06  1.195490e+06   
Diện tích   3.358900e+03  6.177700e+03  1.668000e+03  1.284900e+03   
population  8.330803e+06  1.358085e+06  1.836270e+06  1.195490e+06   
Mật độ      2.480218e+03  2.198367e+02  1.100881e+03  9.304148e+02   

            TP.Hồ Chí Minh  
Dân số        9.411805e+06  
Diện tích     2.061000e+03  
population    9.411805e+06  
Mật độ        4.566621e+03

In [12]:
print("Cách 1, sử dụng chuyển vị:", data.T.values[1])
print("Cách 2, sử dụng chỉ mục (index):", data['Diện tích'].values)

Cách 1, sử dụng chuyển vị: [3358.9 6177.7 1668.  1284.9 2061. ]
Cách 2, sử dụng chỉ mục (index): [3358.9 6177.7 1668.  1284.9 2061. ]


In [13]:
####vd4.4.2.3
#Sử dụng loc 
print(data) 
#Lấy hàng đầu tiên 
print('\n Dữ liệu của Hà Nội:\n',data.loc['Hà Nội']) 
#Lấy dữ liệu 3 hàng đầu tiên
print("\n Dữ liệu của Hà Nội, Quảng Ninh và Nam Định:\n",data.loc[:'Nam Định']) 
#Dữ liệu của 2 hàng và 2 cột đầu tiên 
print("\nDữ liệu dân số, diện tích của Hà Nội, Quảng Ninh:\n",data.loc[:'Quảng Ninh',:'Diện tích']) 
#Lấy dữ liệu của tất cả các hàng và các cột cuối cùng 
print("\n Mật độ dân số các Tỉnh/Thành phố:\n",data.loc[:,'Mật độ']) 

                 Dân số  Diện tích  population       Mật độ
Hà Nội          8330803     3358.9     8330803  2480.217631
Quảng Ninh      1358085     6177.7     1358085   219.836671
Nam Định        1836270     1668.0     1836270  1100.881295
Đà Nẵng         1195490     1284.9     1195490   930.414818
TP.Hồ Chí Minh  9411805     2061.0     9411805  4566.620573

 Dữ liệu của Hà Nội:
 Dân số        8.330803e+06
Diện tích     3.358900e+03
population    8.330803e+06
Mật độ        2.480218e+03
Name: Hà Nội, dtype: float64

 Dữ liệu của Hà Nội, Quảng Ninh và Nam Định:
              Dân số  Diện tích  population       Mật độ
Hà Nội      8330803     3358.9     8330803  2480.217631
Quảng Ninh  1358085     6177.7     1358085   219.836671
Nam Định    1836270     1668.0     1836270  1100.881295

Dữ liệu dân số, diện tích của Hà Nội, Quảng Ninh:
              Dân số  Diện tích
Hà Nội      8330803     3358.9
Quảng Ninh  1358085     6177.7

 Mật độ dân số các Tỉnh/Thành phố:
 Hà Nội            2480.2176

In [14]:
#sử dụng với iloc
print(data) 
#Lấy hàng đầu tiên 
print("\nDữ liệu của thủ đô Hà Nội:\n",data.iloc[0]) 
#Lấy dữ liệu 3 hàng đầu tiên
print("\nDữ liệu của Hà Nội, Quảng Ninh và Nam Định:\n",data.iloc[0:3]) 
#Lấy dữ liệu 2 hàng, 2 cột đầu tiên
print("\nDữ liệu dân số và diện tích của Hà Nội và Quảng Ninh:\n",data.iloc[:2,:2])
#Lấy dữ liệu về mật độ dân số của các tỉnh còn lại
print("Mật độ dân số của các tỉnh/thành phố:\n",data.iloc[:,-1]) 

                 Dân số  Diện tích  population       Mật độ
Hà Nội          8330803     3358.9     8330803  2480.217631
Quảng Ninh      1358085     6177.7     1358085   219.836671
Nam Định        1836270     1668.0     1836270  1100.881295
Đà Nẵng         1195490     1284.9     1195490   930.414818
TP.Hồ Chí Minh  9411805     2061.0     9411805  4566.620573

Dữ liệu của thủ đô Hà Nội:
 Dân số        8.330803e+06
Diện tích     3.358900e+03
population    8.330803e+06
Mật độ        2.480218e+03
Name: Hà Nội, dtype: float64

Dữ liệu của Hà Nội, Quảng Ninh và Nam Định:
              Dân số  Diện tích  population       Mật độ
Hà Nội      8330803     3358.9     8330803  2480.217631
Quảng Ninh  1358085     6177.7     1358085   219.836671
Nam Định    1836270     1668.0     1836270  1100.881295

Dữ liệu dân số và diện tích của Hà Nội và Quảng Ninh:
              Dân số  Diện tích
Hà Nội      8330803     3358.9
Quảng Ninh  1358085     6177.7
Mật độ dân số của các tỉnh/thành phố:
 Hà Nội          

#### VD4.4.2.4


In [17]:
#Lấy dữ liệu dân số và mật độ các tỉnh/TP có diện tích > 2000km2. 
print("\n#1.  Dữ liệu dân số và mật độ của Tỉnh/TP mà diện tích >2000km2: \n")
print(data.loc[data['Diện tích'] > 2000, ['Dân số', 'Mật độ']])


#1.  Dữ liệu dân số và mật độ của Tỉnh/TP mà diện tích >2000km2: 

                 Dân số       Mật độ
Hà Nội          8330803  2480.217631
Quảng Ninh      1358085   219.836671
TP.Hồ Chí Minh  9411805  4566.620573


In [18]:
#Lấy dữ liệu Tỉnh/TP có mật độ <1000 và dân số >1000000
print("Diện tích các tỉnh/TP có mật độ < 1000 và dân số > 1 triệu:\n",data.loc[(data['Mật độ']<1000) & (data['Diện tích'] > 1000), ['Diện tích', 'Mật độ']]) 


Diện tích các tỉnh/TP có mật độ < 1000 và dân số > 1 triệu:
             Diện tích      Mật độ
Quảng Ninh     6177.7  219.836671
Đà Nẵng        1284.9  930.414818


#### Ví dụ 4.4.2.6

In [19]:
#Sử dụng slicing
print(data[0:2])

             Dân số  Diện tích  population       Mật độ
Hà Nội      8330803     3358.9     8330803  2480.217631
Quảng Ninh  1358085     6177.7     1358085   219.836671


In [20]:
print(data[data['Mật độ']>1000])   #masking

                 Dân số  Diện tích  population       Mật độ
Hà Nội          8330803     3358.9     8330803  2480.217631
Nam Định        1836270     1668.0     1836270  1100.881295
TP.Hồ Chí Minh  9411805     2061.0     9411805  4566.620573
